//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  import type { TinaMarkdownContent } from 'tinacms/dist/rich-text';
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
  /** A rich-text document, renderable by TinaMarkdown */
  RichText: { input: TinaMarkdownContent; output: TinaMarkdownContent; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  site: Site;
  siteConnection: SiteConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
};

export type DocumentFilter = {
  site?: InputMaybe<SiteFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Site | Folder;

export type SiteHero = {
  __typename?: 'SiteHero';
  text?: Maybe<Scalars['String']['output']>;
};

export type SiteAboutPillars = {
  __typename?: 'SiteAboutPillars';
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
};

export type SiteAbout = {
  __typename?: 'SiteAbout';
  image?: Maybe<Scalars['String']['output']>;
  lead?: Maybe<Scalars['String']['output']>;
  p1?: Maybe<Scalars['String']['output']>;
  p2?: Maybe<Scalars['String']['output']>;
  pillars?: Maybe<Array<Maybe<SiteAboutPillars>>>;
};

export type SitePrograms = {
  __typename?: 'SitePrograms';
  image?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
};

export type SiteEvents = {
  __typename?: 'SiteEvents';
  day?: Maybe<Scalars['String']['output']>;
  month?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  time?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
};

export type SiteImpact = {
  __typename?: 'SiteImpact';
  number?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type SiteDirectors = {
  __typename?: 'SiteDirectors';
  photo?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
};

export type SiteOfficers = {
  __typename?: 'SiteOfficers';
  photo?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
};

export type SiteGallery = {
  __typename?: 'SiteGallery';
  image?: Maybe<Scalars['String']['output']>;
};

export type SiteInvolve = {
  __typename?: 'SiteInvolve';
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  buttonText?: Maybe<Scalars['String']['output']>;
  buttonUrl?: Maybe<Scalars['String']['output']>;
};

export type SiteContact = {
  __typename?: 'SiteContact';
  label?: Maybe<Scalars['String']['output']>;
  value?: Maybe<Scalars['String']['output']>;
};

export type Site = Node & Document & {
  __typename?: 'Site';
  hero?: Maybe<SiteHero>;
  about?: Maybe<SiteAbout>;
  programs?: Maybe<Array<Maybe<SitePrograms>>>;
  events?: Maybe<Array<Maybe<SiteEvents>>>;
  impact?: Maybe<Array<Maybe<SiteImpact>>>;
  directors?: Maybe<Array<Maybe<SiteDirectors>>>;
  officers?: Maybe<Array<Maybe<SiteOfficers>>>;
  gallery?: Maybe<Array<Maybe<SiteGallery>>>;
  involve?: Maybe<Array<Maybe<SiteInvolve>>>;
  contact?: Maybe<Array<Maybe<SiteContact>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteHeroFilter = {
  text?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteAboutPillarsFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type SiteAboutFilter = {
  image?: InputMaybe<ImageFilter>;
  lead?: InputMaybe<StringFilter>;
  p1?: InputMaybe<StringFilter>;
  p2?: InputMaybe<StringFilter>;
  pillars?: InputMaybe<SiteAboutPillarsFilter>;
};

export type SiteProgramsFilter = {
  image?: InputMaybe<ImageFilter>;
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type SiteEventsFilter = {
  day?: InputMaybe<StringFilter>;
  month?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  time?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
};

export type SiteImpactFilter = {
  number?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type SiteDirectorsFilter = {
  photo?: InputMaybe<ImageFilter>;
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
};

export type SiteOfficersFilter = {
  photo?: InputMaybe<ImageFilter>;
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
};

export type SiteGalleryFilter = {
  image?: InputMaybe<ImageFilter>;
};

export type SiteInvolveFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  buttonText?: InputMaybe<StringFilter>;
  buttonUrl?: InputMaybe<StringFilter>;
};

export type SiteContactFilter = {
  label?: InputMaybe<StringFilter>;
  value?: InputMaybe<StringFilter>;
};

export type SiteFilter = {
  hero?: InputMaybe<SiteHeroFilter>;
  about?: InputMaybe<SiteAboutFilter>;
  programs?: InputMaybe<SiteProgramsFilter>;
  events?: InputMaybe<SiteEventsFilter>;
  impact?: InputMaybe<SiteImpactFilter>;
  directors?: InputMaybe<SiteDirectorsFilter>;
  officers?: InputMaybe<SiteOfficersFilter>;
  gallery?: InputMaybe<SiteGalleryFilter>;
  involve?: InputMaybe<SiteInvolveFilter>;
  contact?: InputMaybe<SiteContactFilter>;
};

export type SiteConnectionEdges = {
  __typename?: 'SiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site>;
};

export type SiteConnection = Connection & {
  __typename?: 'SiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSite: Site;
  createSite: Site;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationCreateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};

export type DocumentUpdateMutation = {
  site?: InputMaybe<SiteMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  site?: InputMaybe<SiteMutation>;
};

export type SiteHeroMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
};

export type SiteAboutPillarsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type SiteAboutMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
  p1?: InputMaybe<Scalars['String']['input']>;
  p2?: InputMaybe<Scalars['String']['input']>;
  pillars?: InputMaybe<Array<InputMaybe<SiteAboutPillarsMutation>>>;
};

export type SiteProgramsMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type SiteEventsMutation = {
  day?: InputMaybe<Scalars['String']['input']>;
  month?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  time?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
};

export type SiteImpactMutation = {
  number?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type SiteDirectorsMutation = {
  photo?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
};

export type SiteOfficersMutation = {
  photo?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
};

export type SiteGalleryMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
};

export type SiteInvolveMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  buttonText?: InputMaybe<Scalars['String']['input']>;
  buttonUrl?: InputMaybe<Scalars['String']['input']>;
};

export type SiteContactMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  value?: InputMaybe<Scalars['String']['input']>;
};

export type SiteMutation = {
  hero?: InputMaybe<SiteHeroMutation>;
  about?: InputMaybe<SiteAboutMutation>;
  programs?: InputMaybe<Array<InputMaybe<SiteProgramsMutation>>>;
  events?: InputMaybe<Array<InputMaybe<SiteEventsMutation>>>;
  impact?: InputMaybe<Array<InputMaybe<SiteImpactMutation>>>;
  directors?: InputMaybe<Array<InputMaybe<SiteDirectorsMutation>>>;
  officers?: InputMaybe<Array<InputMaybe<SiteOfficersMutation>>>;
  gallery?: InputMaybe<Array<InputMaybe<SiteGalleryMutation>>>;
  involve?: InputMaybe<Array<InputMaybe<SiteInvolveMutation>>>;
  contact?: InputMaybe<Array<InputMaybe<SiteContactMutation>>>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type SiteHeroFilter = {
  text?: StringFilter | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type SiteAboutPillarsFilter = {
  title?: StringFilter | null | undefined;
  text?: StringFilter | null | undefined;
};

export type SiteAboutFilter = {
  image?: ImageFilter | null | undefined;
  lead?: StringFilter | null | undefined;
  p1?: StringFilter | null | undefined;
  p2?: StringFilter | null | undefined;
  pillars?: SiteAboutPillarsFilter | null | undefined;
};

export type SiteProgramsFilter = {
  image?: ImageFilter | null | undefined;
  title?: StringFilter | null | undefined;
  text?: StringFilter | null | undefined;
};

export type SiteEventsFilter = {
  day?: StringFilter | null | undefined;
  month?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  time?: StringFilter | null | undefined;
  location?: StringFilter | null | undefined;
};

export type SiteImpactFilter = {
  number?: StringFilter | null | undefined;
  label?: StringFilter | null | undefined;
};

export type SiteDirectorsFilter = {
  photo?: ImageFilter | null | undefined;
  name?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
  bio?: StringFilter | null | undefined;
};

export type SiteOfficersFilter = {
  photo?: ImageFilter | null | undefined;
  name?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
  bio?: StringFilter | null | undefined;
};

export type SiteGalleryFilter = {
  image?: ImageFilter | null | undefined;
};

export type SiteInvolveFilter = {
  title?: StringFilter | null | undefined;
  text?: StringFilter | null | undefined;
  buttonText?: StringFilter | null | undefined;
  buttonUrl?: StringFilter | null | undefined;
};

export type SiteContactFilter = {
  label?: StringFilter | null | undefined;
  value?: StringFilter | null | undefined;
};

export type SiteFilter = {
  hero?: SiteHeroFilter | null | undefined;
  about?: SiteAboutFilter | null | undefined;
  programs?: SiteProgramsFilter | null | undefined;
  events?: SiteEventsFilter | null | undefined;
  impact?: SiteImpactFilter | null | undefined;
  directors?: SiteDirectorsFilter | null | undefined;
  officers?: SiteOfficersFilter | null | undefined;
  gallery?: SiteGalleryFilter | null | undefined;
  involve?: SiteInvolveFilter | null | undefined;
  contact?: SiteContactFilter | null | undefined;
};

export type SitePartsFragment = { __typename: 'Site', hero: { __typename: 'SiteHero', text: string | null } | null, about: { __typename: 'SiteAbout', image: string | null, lead: string | null, p1: string | null, p2: string | null, pillars: Array<{ __typename: 'SiteAboutPillars', title: string | null, text: string | null } | null> | null } | null, programs: Array<{ __typename: 'SitePrograms', image: string | null, title: string | null, text: string | null } | null> | null, events: Array<{ __typename: 'SiteEvents', day: string | null, month: string | null, title: string | null, time: string | null, location: string | null } | null> | null, impact: Array<{ __typename: 'SiteImpact', number: string | null, label: string | null } | null> | null, directors: Array<{ __typename: 'SiteDirectors', photo: string | null, name: string | null, role: string | null, bio: string | null } | null> | null, officers: Array<{ __typename: 'SiteOfficers', photo: string | null, name: string | null, role: string | null, bio: string | null } | null> | null, gallery: Array<{ __typename: 'SiteGallery', image: string | null } | null> | null, involve: Array<{ __typename: 'SiteInvolve', title: string | null, text: string | null, buttonText: string | null, buttonUrl: string | null } | null> | null, contact: Array<{ __typename: 'SiteContact', label: string | null, value: string | null } | null> | null };

export type SiteQueryVariables = Exact<{
  relativePath: string;
}>;


export type SiteQuery = { site: { __typename: 'Site', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero: { __typename: 'SiteHero', text: string | null } | null, about: { __typename: 'SiteAbout', image: string | null, lead: string | null, p1: string | null, p2: string | null, pillars: Array<{ __typename: 'SiteAboutPillars', title: string | null, text: string | null } | null> | null } | null, programs: Array<{ __typename: 'SitePrograms', image: string | null, title: string | null, text: string | null } | null> | null, events: Array<{ __typename: 'SiteEvents', day: string | null, month: string | null, title: string | null, time: string | null, location: string | null } | null> | null, impact: Array<{ __typename: 'SiteImpact', number: string | null, label: string | null } | null> | null, directors: Array<{ __typename: 'SiteDirectors', photo: string | null, name: string | null, role: string | null, bio: string | null } | null> | null, officers: Array<{ __typename: 'SiteOfficers', photo: string | null, name: string | null, role: string | null, bio: string | null } | null> | null, gallery: Array<{ __typename: 'SiteGallery', image: string | null } | null> | null, involve: Array<{ __typename: 'SiteInvolve', title: string | null, text: string | null, buttonText: string | null, buttonUrl: string | null } | null> | null, contact: Array<{ __typename: 'SiteContact', label: string | null, value: string | null } | null> | null } };

export type SiteConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: SiteFilter | null | undefined;
}>;


export type SiteConnectionQuery = { siteConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Site', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero: { __typename: 'SiteHero', text: string | null } | null, about: { __typename: 'SiteAbout', image: string | null, lead: string | null, p1: string | null, p2: string | null, pillars: Array<{ __typename: 'SiteAboutPillars', title: string | null, text: string | null } | null> | null } | null, programs: Array<{ __typename: 'SitePrograms', image: string | null, title: string | null, text: string | null } | null> | null, events: Array<{ __typename: 'SiteEvents', day: string | null, month: string | null, title: string | null, time: string | null, location: string | null } | null> | null, impact: Array<{ __typename: 'SiteImpact', number: string | null, label: string | null } | null> | null, directors: Array<{ __typename: 'SiteDirectors', photo: string | null, name: string | null, role: string | null, bio: string | null } | null> | null, officers: Array<{ __typename: 'SiteOfficers', photo: string | null, name: string | null, role: string | null, bio: string | null } | null> | null, gallery: Array<{ __typename: 'SiteGallery', image: string | null } | null> | null, involve: Array<{ __typename: 'SiteInvolve', title: string | null, text: string | null, buttonText: string | null, buttonUrl: string | null } | null> | null, contact: Array<{ __typename: 'SiteContact', label: string | null, value: string | null } | null> | null } | null } | null> | null } };

export const SitePartsFragmentDoc = gql`
    fragment SiteParts on Site {
  __typename
  hero {
    __typename
    text
  }
  about {
    __typename
    image
    lead
    p1
    p2
    pillars {
      __typename
      title
      text
    }
  }
  programs {
    __typename
    image
    title
    text
  }
  events {
    __typename
    day
    month
    title
    time
    location
  }
  impact {
    __typename
    number
    label
  }
  directors {
    __typename
    photo
    name
    role
    bio
  }
  officers {
    __typename
    photo
    name
    role
    bio
  }
  gallery {
    __typename
    image
  }
  involve {
    __typename
    title
    text
    buttonText
    buttonUrl
  }
  contact {
    __typename
    label
    value
  }
}
    `;
export const SiteDocument = gql`
    query site($relativePath: String!) {
  site(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteParts
  }
}
    ${SitePartsFragmentDoc}`;
export const SiteConnectionDocument = gql`
    query siteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteFilter) {
  siteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteParts
      }
    }
  }
}
    ${SitePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      site(variables: SiteQueryVariables, options?: C): Promise<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}> {
        return requester<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}, SiteQueryVariables>(SiteDocument, variables, options);
      },
    siteConnection(variables?: SiteConnectionQueryVariables, options?: C): Promise<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}, SiteConnectionQueryVariables>(SiteConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  